SCENARIO = "scenario"
COUNTRY_CODE = "country_code"
IU_NAME = "iu_name"
YEAR_ID = "year_id"
MEASURE = "measure"
PROCESSED_PREVALENCE = "processed_prevalence"
PROB_UNDER_THRESHOLD_MEASURE_NAME = "prob_under_threshold_measure_name"
